version: "3"
services:
  client:
    container_name: client
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongodb"
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ""
      ME_CONFIG_MONGODB_ADMINPASSWORD: ""
      UALCMP_SERVER: "192.168.86.210"
      UALCMP_PORT: 30000
    depends_on: 
      - mongodb
    links:
      - mongodb
    image: uminhonetedge/proxy_client:1.0.8
    ports:
      - "5005:5005"
    networks:
      - mynetwork
  client_ui:
    container_name: client_ui
    restart: always
    environment:
      REACT_APP_DEVICE_APP_HOSTNAME: "127.0.0.1"
      REACT_APP_DEVICE_APP_PORT: "5005"
    depends_on: 
      - client
    links:
      - client
    image: uminhonetedge/proxy_client_ui:1.2.21
    ports:
      - "3000:3000"
    networks:
      - mynetwork  
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""    
    expose:
      - 27017
    container_name: mongo
    restart: always
    volumes:
      - ../data:/data/db
    networks:
      - mynetwork
  mongoexpress:
    image: mongo-express
    ports:
      - 8081:8081
    expose:
      - 8081
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongodb"
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ""
      ME_CONFIG_MONGODB_ADMINPASSWORD: ""
    container_name: express
    restart: always
    volumes:
      - ../data:/data/express
    networks:
      - mynetwork
      
volumes:
 mongodb:

networks:
  mynetwork:
